const FETCH_TRENDING_NEWS = {
  FETCH_TRENDING_NEWS: 'FETCH_TRENDING_NEWS_LOADING',
  FETCH_TRENDING_NEWS_SUCCESS: 'FETCH_TRENDING_NEWS_SUCCESS',
  FETCH_TRENDING_NEWS_FAILED: 'FETCH_TRENDING_NEWS_LOAD_FAIL',
};
const FETCH_NEWS = {
  FETCH_NEWS: 'FETCH_NEWS_LOADING',
  FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS',
  FETCH_NEWS_FAILED: 'FETCH_NEWS_LOAD_FAIL',
};

const FILTER_NEWS = {
  FILTER_NEWS: 'FILTER_NEWS_LOADING',
  FILTER_NEWS_SUCCESS: 'FILTER_NEWS_SUCCESS',
  FILTER_NEWS_FAILED: 'FILTER_NEWS_LOAD_FAIL',
};

const ON_SCREEN_CHANGED = 'NEWS/ON_SCREEN_CHANGED';

export { FETCH_TRENDING_NEWS, FETCH_NEWS, FILTER_NEWS, ON_SCREEN_CHANGED };
